```{r}
#Load Libraries 
library(tidyverse)
library(lubridate)
```



```{r}
#Load data 
melb_data <- read.csv("melb_data.csv")
```


```{r}
#Mutate price average for each suburbs 
melb_data_clean <- melb_data %>% 
  group_by(Suburb) %>%  
  mutate(Average_Price = mean(Price),
         Date = dmy(Date),
         Year = year(Date),
         Month = month(Date),
         Method = recode_factor(Method,
                                "S" = "Property Sold", 
                                "SP" = "Property Sold Prior",
                                "PI" = "Property Passed In",
                                "PN" = "Sold Prior Not Disclosed",
                                "SN" = "Sold Not Disclosed", 
                                "NB" = "No Bid", 
                                "VB" = "Vendor Bid",
                                "W" = "Withdrawn Priod Auction",
                                "SA" = "Sold After Auction", 
                                "SS" = "Sold After Auction Price Not Disclosed"),
         Avg_Price_Room = Price/Rooms,
         Avg_Price_Land = Price/Landsize,
         Avg_Land_Sub = mean(Landsize),
         Room_Bathroom = paste(Rooms,Bathroom, sep = ",")) %>% 
  select(-"BuildingArea", "YearBuilt") %>% 
  na.omit()
  
```

```{r}
#WRITE CSV 
melb_data_clean <- melb_data_clean %>% ungroup()

write.csv(melb_data_clean, file = "Melbourne_Pricing_House.csv",
          row.names = TRUE)
```



